spring.application.name=minicorebank

spring.datasource.url=jdbc:mysql://localhost:3306/minicorebank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=#Datta2611
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.h2.console.settings.web-allow-others=true
spring.h2.console.enabled=true

spring.sql.init.mode=always
spring.jpa.show-sql=true
server.port=8080



jwt.secret=8f2d94a7c6be12ff45a98712dd98aa76f43eaa1287c99abfe83cd23b1afser23
jwt.accessExpirationMs=900000
jwt.refreshExpirationMs=1209600000

# springdoc
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Security / login protection
security.maxFailedLoginAttempts=5
security.lockMinutes=15