spring.application.name=minicorebank
server.port=8082
server.servlet.context-path=/minicorebank

# ===============================
# MongoDB Atlas Configuration
# ===============================
spring.data.mongodb.uri=mongodb+srv://dattatrayjamkhande23:3jo7q6OwSJf3EK3O@cluster0.kpbpxti.mongodb.net/minicorebankdb
spring.data.mongodb.auto-index-creation=true

# ===============================
# Disable JPA / Hibernate
# ===============================
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# ===============================
# Logging
# ===============================
logging.level.web=DEBUG

# ===============================
# JWT Configuration
# ===============================
jwt.secret=8f2d94a7c6be12ff45a98712dd98aa76f43eaa1287c99abfe83cd23b1afser23
jwt.accessExpirationMs=900000
jwt.refreshExpirationMs=1209600000

# ===============================
# SpringDoc / Swagger
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# ===============================
# Security Settings
# ===============================
security.maxFailedLoginAttempts=5
security.lockMinutes=15

logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.org.springframework.data.mongodb.repository.query=INFO
spring.data.mongodb.ssl.enabled=true

# ===============================
# Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=minicorebank-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.main.allow-bean-definition-overriding=true

#Actuater
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=MiniCoreBank

#Grafana username: admin Pass: Datta123